
version: '3.1'

services:

  db:
    image: mysql:5.7.44
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: controlescolar
      MYSQL_USER: terry
      MYSQL_PASSWORD: 123456
    volumes: 
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306